# Generated by Django 3.1.7 on 2021-03-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourism',
            name='price',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AlterField(
            model_name='tourism',
            name='img',
            field=models.ImageField(upload_to='templates'),
        ),
        migrations.AlterField(
            model_name='tourism',
            name='name',
            field=models.CharField(default='Trekking Shoes', max_length=100),
        ),
    ]
