# Generated by Django 3.1.7 on 2021-03-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210317_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='header_image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
