# Generated by Django 3.1.7 on 2021-04-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210407_1539'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
